[package]
name = "dictionary_compression"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
ahash = "0.8.11"
varint-simd = { version = "0.4.0", features = ["native-optimizations"] }
